# Generated by Django 3.2.10 on 2021-12-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UnitSystem', models.CharField(blank=True, choices=[('CFBC', 'CFBC'), ('AHS', 'AHS'), ('MHS', 'MHS'), ('LIME', 'LIME'), ('UB', 'UB'), ('HRSG', 'HRSG'), ('GT', 'GT'), ('STG', 'STG'), ('CPP-BOP', 'CPP-BOP'), ('CFBC-BOP', 'CFBC-BOP'), ('IA/PA/IG', 'IA/PA/IG'), ('SW/PW', 'SW/PW'), ('Switch-Yard', 'Switch-Yard'), ('SS-9', 'SS-9'), ('SS-10', 'SS-10'), ('SS-29', 'SS-29'), ('SS-30', 'SS-30'), ('MRS-80', 'MRS-80'), ('VAM/Chiller', 'VAM/Chiller'), ('AHU/APU', 'AHU/APU'), ('Fire', 'Fire'), ('OWS', 'OWS'), ('OT-DRAIN', 'OT-DRAIN'), ('TRAFO', 'TRAFO'), ('RFG', 'RFG'), ('NG', 'NG'), ('LCO', 'LCO'), ('NAPHTHA', 'NAPHTHA'), ('HSD', 'HSD'), ('Flare', 'Flare'), ('Pet-Coke', 'Pet-Coke')], max_length=20)),
                ('Department', models.CharField(blank=True, choices=[('MMD', 'MMD'), ('EMD', 'EMD'), ('IMD', 'IMD')], max_length=20)),
                ('Permit', models.CharField(blank=True, choices=[('Cold', 'Cold'), ('Hot', 'Hot')], max_length=20)),
                ('SAPNum', models.CharField(blank=True, max_length=60)),
                ('Description', models.CharField(blank=True, max_length=500)),
                ('Remarks', models.CharField(blank=True, choices=[('CM', 'CM'), ('PM', 'PM'), ('NMS', 'NMS'), ('SD', 'SD'), ('Defect', 'Defect'), ('HouseKeeping', 'HouseKeeping'), ('Lubrication', 'Lubrication')], max_length=20)),
                ('Priority', models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20)),
                ('Status', models.CharField(blank=True, choices=[('Open', 'Open'), ('Inprogress', 'Inprogress'), ('Closed', 'Closed')], max_length=20)),
                ('CreatedDate', models.CharField(blank=True, max_length=20)),
                ('LastActivity', models.CharField(blank=True, max_length=20)),
                ('MonthYearID', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
