# Generated by Django 3.2.10 on 2021-12-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyplanningboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='Permit',
            field=models.CharField(blank=True, choices=[('Cold', 'Cold'), ('Hot', 'Hot'), ('Cofined', 'Cofined')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='Remarks',
            field=models.CharField(blank=True, choices=[('CM', 'CM'), ('PM', 'PM'), ('NMS', 'NMS'), ('MI', 'MI'), ('SD', 'SD'), ('GT-MI', 'GT-MI'), ('Defect', 'Defect'), ('HouseKeeping', 'HouseKeeping'), ('Lubrication', 'Lubrication')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='Status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Inprogress', 'Inprogress'), ('Completed', 'Completed')], max_length=20),
        ),
    ]
