# Generated by Django 3.2.10 on 2021-12-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyplanningboard', '0002_auto_20211223_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='Permit',
            field=models.CharField(blank=True, choices=[('Cold', 'Cold'), ('Hot', 'Hot'), ('Confined', 'Confined')], max_length=20),
        ),
    ]
